name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t subproblem/fitness-tracking-app .

      - name: Publish Image to Docker Hub
        run: docker push subproblem/fitness-tracking-app:latest

  deploy:
    needs: build
    runs-on: TestRunner
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull subproblem/fitness-tracking-app:latest

      - name: Delete Old Container
        run: docker rm -f springboot-fitness-tracking-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --restart always --name springboot-fitness-tracking-app-container --network mynetwork subproblem/fitness-tracking-app:latest
